 const CUSTOMER = "CUSTOMER"
 const RESTAURANT_OWNER = "RESTAURANT_OWNER"
 const ADMINISTRATOR = "ADMINISTRATOR"
 const OPERATOR = "OPERATOR"

 module.exports = {
     CUSTOMER,
     RESTAURANT_OWNER,
     ADMINISTRATOR,
     OPERATOR
 }